version: "3.7"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Database configuration
    # DB_HOST=host.docker.internal
      - DB_HOST=ep-solitary-haze-a1nwtzso-pooler.ap-southeast-1.aws.neon.tech
      - DB_PORT=5432
      - DB_USER=neondb_owner
      - DB_PASS=npg_afMioT1F7YIE
      - DB_NAME=neondb
      - DATABASE_URL=postgresql://postgres:hieunt04lm@db.rakswdmeiapnarrdohza.supabase.co:5432/postgres

      # JWT configuration
      - ACCESS_TOKEN_SECRET=IDontKnowHowButTheyFoundMe
      - REFRESH_TOKEN_SECRET=ArcticMonkeys

      #User_service url
      # USER_SERVICE_URL=https://user-service-8iwy.onrender.com/users
      - USER_SERVICE_URL=http://localhost:4000/users

      # Server configuration
      - PORT=8080

      - BOOTSTRAP_HOST=pkc-619z3.us-east1.gcp.confluent.cloud:9092
      - KAFKA_USERNAME=CM4OQWTDJLRKDSON
      - KAFKA_PASSWORD=cfltf3jK6fqWRO37G7VBIY+OQg4w51+plkHV8ATlMRAhoPb4eVK6OPBbI6MgX5aQ

      - REDIS_ADDRESS=redis-10166.c323.us-east-1-2.ec2.redns.redis-cloud.com:10166
      - REDIS_PASSWORD=YUDWWMPA7YUdWUxskx7qnlvF3eNmqb0g
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  prometheus:
      image: prom/prometheus
      container_name: prometheus
      ports:
        - "9090:9090" # Prometheus UI and scraping
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--web.enable-lifecycle' # Enable /-/reload endpoint for config changes


  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - ./logs:/app/logs
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.3.1
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
      - prometheus